### ISSUE TITLE
Store logo text visibility issue on transparent header

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Lauren---Internal--Apr-28th#1]
Bug - Store logo text not clear visible when header get transparent.
Exp - Logo text should be clear visible if header get transparent.
Ref Link - https://drive.google.com/file/d/1hH5SOYIIho7DVzdRmw0rJMLl1X3WhkwX/view

**Comment by devAbhishekYadav** [comment]
https://www.awesomescreenshot.com/video/8494227?key=736c39a73dd89a38bb84504ce233329e
resolved

**Comment by ankitcedcoss** [comment]
Bug Fixed
