### ISSUE TITLE
spacing issue on cart drawer

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Lauren---Internal--Apr-28th#12]
Bug - less spacings showing between buttons.
Exp - Add spacing between buttons on cart drawer.
Ref Link - https://nimb.ws/WHkF0v

**Comment by devAbhishekYadav** [comment]
![image](https://user-images.githubusercontent.com/89765850/164206295-adc3d159-7c0a-4315-8e2f-51b0b7bc4a1c.png)

proper spacing is there

**Comment by ankitcedcoss** [comment]
Bug Fixed
