### ISSUE TITLE
success message issue on newsletter 

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Lauren---Internal--Apr-28th#15]
Bug - If user enters email and click on subscribe then showing message "field can't be blank".
Exp - If newsletter is not blank and email is in correct format then should show proper success message.
Ref Link - https://drive.google.com/file/d/1nxfMZC-5En3kOncBWyeqi95DxsNOHEj4/view

**Comment by devAbhishekYadav** [comment]
![Screenshot from 2022-04-20 15-39-39](https://user-images.githubusercontent.com/89765850/164205267-72ccaa2f-2ec1-48c9-9fa5-0812afe6dd48.png)
Success message is showing

**Comment by devAbhishekYadav** [comment]
here is the video of correct success message demonstration 
https://www.awesomescreenshot.com/video/8493953?key=cfd5203cfd24ddae18f33d11c4acf38b

**Comment by ankitcedcoss** [comment]
Bug Fixed
